"use client";
import { useEffect, useState } from "react";
type Analysis = { matchScore: number; recommendation: string; strengths: string[]; gaps: string[] };
type Job = { id?: string; title: string; company: string; location: string; url: string; salary: string | null; posted: string | null; applicationStatus?: "SAVED" | "APPLIED" | "NOT_PURSUING"; appliedAt?: string | null; analysis?: Analysis };
type Result = { jobs?: Job[]; total?: number; error?: string };
const profileUrl = "https://www.linkedin.com/in/patelkajal2222/";
function prompt(job: Job) { return `Find 10 relevant LinkedIn profiles at ${job.company} who could be useful for a referral or warm connection for a ${job.title} role.\n\nFirst review my LinkedIn profile: ${profileUrl}\nUse it to understand my skills, career narrative, personality, and communication style from public posts.\n\nFor each person provide their name, current title, direct LinkedIn profile URL, why they are relevant, the best connection angle, and a concise send-ready personalized LinkedIn outreach message in my voice. Do not invent URLs or details; label anything that needs verification.`; }
function when(value?: string | null) { return value ? new Date(value).toLocaleDateString(undefined, { month: "short", day: "numeric" }) : ""; }

export default function ListingsPage() {
  const [jobs, setJobs] = useState<Job[]>([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [copied, setCopied] = useState<string | null>(null); const [updating, setUpdating] = useState<string | null>(null);
  async function load() { setLoading(true); try { const response = await fetch("/api/jobs?page=1&pageSize=50&source=all"); const data = await response.json().catch(() => ({} as Result)); const fallback = JSON.parse(window.sessionStorage.getItem("latest-job-search") || "[]") as Job[]; setJobs(data.jobs?.length ? data.jobs : fallback); setTotal(data.total ?? fallback.length); if (!response.ok) setError(data.error || "Listings could not be loaded."); } catch { setError("Listings could not be loaded."); } finally { setLoading(false); } }
  // Client-only persisted listing load.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, []);
  async function setStatus(job: Job, status: "APPLIED" | "NOT_PURSUING") { if (!job.id) return; setUpdating(job.id); try { const r = await fetch(`/api/jobs/${job.id}/application`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ status }) }); const data = await r.json().catch(() => ({} as { appliedAt?: string; error?: string })); if (!r.ok) throw new Error(data.error); setJobs((items) => items.map((item) => item.id === job.id ? { ...item, applicationStatus: status, appliedAt: data.appliedAt || null } : item)); } catch { setError("Status could not be saved."); } finally { setUpdating(null); } }
  async function copy(job: Job) { try { await navigator.clipboard.writeText(prompt(job)); setCopied(job.id || job.url); window.setTimeout(() => setCopied(null), 1800); } catch { setError("Prompt could not be copied."); } }
  const analyzed = jobs.filter((job) => job.analysis).length; const sorted = [...jobs].sort((a, b) => (b.analysis?.matchScore || 0) - (a.analysis?.matchScore || 0));
  return <main className="min-h-screen bg-[#f6f7f2] px-6 py-10 text-[#17221c] sm:px-10 lg:px-16"><div className="mx-auto max-w-5xl"><p className="text-sm font-medium text-[#c06c42]">Job discovery</p><h1 className="mt-2 text-4xl font-semibold tracking-[-0.04em]">Listings</h1><p className="mt-2 text-[#607064]">{total} saved postings · {analyzed} currently analyzed and shown first by match score.</p>{error && <p className="mt-6 rounded-xl bg-[#fff1eb] px-4 py-3 text-sm text-[#a34f2e]">{error}</p>}{loading ? <p className="mt-10 text-[#7b8b7e]">Loading listings…</p> : <div className="mt-8 grid gap-4">{sorted.map((job, index) => <JobCard copied={copied} job={job} key={job.id || `${job.url}-${index}`} updating={updating === job.id} onCopy={copy} onStatus={setStatus} />)}</div>}</div></main>;
}
function JobCard({ job, copied, updating, onCopy, onStatus }: { job: Job; copied: string | null; updating: boolean; onCopy: (job: Job) => Promise<void>; onStatus: (job: Job, status: "APPLIED" | "NOT_PURSUING") => Promise<void> }) {
  const status = job.applicationStatus || "SAVED";
  const statusLabel = status === "APPLIED" ? `Applied · ${when(job.appliedAt)}` : status === "NOT_PURSUING" ? "Not pursuing" : "Saved";
  return <article className="rounded-3xl border border-[#dbe5d8] bg-white p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-semibold">{job.title}</h2><p className="mt-1 text-[#607064]">{job.company} · {job.location}</p></div><div className="flex shrink-0 items-center gap-2"><span className="rounded-full bg-[#fff5eb] px-3 py-1 text-sm font-semibold text-[#a35d2f]">{statusLabel}</span>{job.url && <a aria-label={`Open ${job.title} posting`} className="inline-flex h-8 w-8 items-center justify-center rounded-full border border-[#b8cdb8] text-[#2f6047] hover:bg-[#f3f7f0]" href={job.url} rel="noreferrer" target="_blank" title="Open job posting"><EyeIcon /></a>}{job.analysis && <span className="rounded-full bg-[#edf6ee] px-3 py-1 text-sm font-semibold text-[#2f6047]">{job.analysis.matchScore}/100</span>}</div></div>{job.salary && <p className="mt-4 text-sm font-medium text-[#47715b]">{job.salary}</p>}{job.analysis ? <details className="mt-4 rounded-2xl bg-[#f3f7f0] p-4"><summary className="cursor-pointer font-semibold text-[#2f6047]">{job.analysis.recommendation} · why this match</summary><p className="mt-3 text-sm text-[#607064]">{job.analysis.strengths[0]}</p></details> : <p className="mt-4 text-sm text-[#7b8b7e]">Match analysis pending for this posting.</p>}<div className="mt-5 flex flex-wrap items-center gap-2">{status !== "APPLIED" && <><button className="rounded-full border border-[#b8cdb8] px-4 py-2 text-sm font-semibold text-[#2f6047] disabled:opacity-50" disabled={updating} onClick={() => void onStatus(job, "APPLIED")} type="button">Mark applied</button><button className="rounded-full border border-[#dbe5d8] px-4 py-2 text-sm font-semibold text-[#607064] disabled:opacity-50" disabled={updating || status === "NOT_PURSUING"} onClick={() => void onStatus(job, "NOT_PURSUING")} type="button">Not pursuing</button></>}<button className="rounded-full border border-[#b8cdb8] px-4 py-2 text-sm font-semibold text-[#2f6047]" onClick={() => void onCopy(job)} title="Copies a prompt to find relevant referral contacts and draft outreach messages." type="button">{copied === (job.id || job.url) ? "Prompt copied ✓" : "Copy referral prompt"}</button></div></article>;
}

function EyeIcon() { return <svg aria-hidden="true" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z" /><circle cx="12" cy="12" r="2.5" /></svg>; }
