"use client";
import { useEffect, useState } from "react";

type Status = { configured: boolean; connected: boolean; address?: string | null; messageCount?: number };
type Action = { id: string; gmailMessageId: string; sender: string | null; subject: string | null; snippet: string | null; isUnread: boolean; receivedAt: string | null; actionType: "REPLY" | "FOLLOW_UP" | "REVIEW"; priority: number; priorityReason: string; draftText: string | null; draftModel: string | null };

export default function ActionOpsPage() {
  const [status, setStatus] = useState<Status | null>(null); const [actions, setActions] = useState<Action[]>([]); const [loading, setLoading] = useState(true); const [syncing, setSyncing] = useState(false); const [drafting, setDrafting] = useState<string | null>(null); const [copied, setCopied] = useState<string | null>(null); const [error, setError] = useState("");
  async function load() { setLoading(true); try { const [s, a] = await Promise.all([fetch("/api/gmail/status"), fetch("/api/gmail/actions")]); const sr = await s.json().catch(() => null); const ar = await a.json().catch(() => ({} as { actions?: Action[]; error?: string })); setStatus(sr); if (!a.ok) setError(ar.error || "Action queue could not be loaded."); else setActions(ar.actions || []); } catch { setError("Action queue could not be loaded."); } finally { setLoading(false); } }
  // External API synchronization intentionally happens after client mount.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, []);
  async function sync() { setSyncing(true); setError(""); try { const r = await fetch("/api/gmail/sync", { method: "POST" }); const x = await r.json().catch(() => ({} as { error?: string })); if (!r.ok) setError(x.error || "Gmail could not be synced."); else await load(); } catch { setError("Gmail could not be synced."); } finally { setSyncing(false); } }
  async function makeDraft(id: string) { setDrafting(id); setError(""); try { const r = await fetch("/api/gmail/actions/draft", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ gmailMessageId: id }) }); const x = await r.json().catch(() => ({} as { draftText?: string; modelUsed?: string; error?: string })); if (!r.ok || !x.draftText) { setError(x.error || "A draft could not be generated."); return; } setActions((items) => items.map((item) => item.gmailMessageId === id ? { ...item, draftText: x.draftText || null, draftModel: x.modelUsed || null } : item)); } catch { setError("A draft could not be generated."); } finally { setDrafting(null); } }
  async function copy(action: Action) { try { await navigator.clipboard.writeText(action.draftText || ""); setCopied(action.gmailMessageId); window.setTimeout(() => setCopied(null), 1800); } catch { setError("Draft could not be copied. Please use your browser's copy command."); } }
  return <main className="min-h-screen bg-[#f6f7f2] px-6 py-10 text-[#17221c] sm:px-10 lg:px-16"><div className="mx-auto max-w-4xl"><p className="text-sm font-medium text-[#c06c42]">Job search operations</p><div className="mt-2 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-4xl font-semibold tracking-[-0.04em]">Action Ops</h1><p className="mt-2 text-[#607064]">A prioritized queue for the job emails that need your attention.</p></div>{status?.connected ? <button className="rounded-full bg-[#2f6047] px-5 py-3 text-sm font-semibold text-white" disabled={syncing} onClick={() => void sync()} type="button">{syncing ? "Syncing…" : "Sync job emails"}</button> : <a className="rounded-full bg-[#2f6047] px-5 py-3 text-sm font-semibold text-white" href={status?.configured ? "/api/gmail/connect" : undefined}>{status?.configured ? "Connect Gmail" : "Gmail setup required"}</a>}</div><section className="mt-8 rounded-3xl border border-[#dbe5d8] bg-white p-6"><p className="text-sm text-[#7b8b7e]">{status?.connected ? `${status.address} connected · ${status.messageCount || 0} job-related messages saved.` : "Gmail is read-only. You review every draft before copying it into Gmail."}</p>{error && <p className="mt-4 rounded-xl bg-[#fff1eb] px-4 py-3 text-sm text-[#a34f2e]">{error}</p>}{loading ? <p className="mt-6 text-[#7b8b7e]">Finding the next best actions…</p> : actions.length === 0 ? <p className="mt-6 rounded-2xl border border-dashed border-[#b8cdb8] p-8 text-center text-sm text-[#7b8b7e]">No job-email actions need attention right now.</p> : <div className="mt-6 grid gap-4">{actions.map((action) => <ActionCard action={action} copied={copied} drafting={drafting} key={action.id} onCopy={copy} onDraft={makeDraft} />)}</div>}</section></div></main>;
}

function sourceForSender(sender: string | null) {
  const value = sender?.toLowerCase() || "";
  if (value.includes("linkedin")) return "LinkedIn";
  if (value.includes("greenhouse")) return "Greenhouse";
  if (value.includes("lever")) return "Lever";
  if (value.includes("ashby")) return "Ashby";
  return null;
}

function ActionCard({ action, copied, drafting, onCopy, onDraft }: { action: Action; copied: string | null; drafting: string | null; onCopy: (action: Action) => Promise<void>; onDraft: (id: string) => Promise<void> }) {
  const level = action.priority >= 90 ? "Urgent" : action.priority >= 75 ? "High priority" : action.priority >= 55 ? "Follow up" : "Review";
  const source = sourceForSender(action.sender);
  return <article className="rounded-2xl border border-[#dbe5d8] bg-[#fbfcfa] p-5"><div className="flex flex-wrap justify-between gap-3"><div><div className="flex gap-2"><span className="rounded-full bg-[#fff1eb] px-2 py-1 text-xs font-semibold text-[#a34f2e]">{level} · {action.priority}/100</span>{source && <span className="inline-flex items-center gap-1 rounded-full bg-[#e8f1fb] px-2 py-1 text-xs font-semibold text-[#0a66c2]"><span className="flex h-4 w-4 items-center justify-center rounded-full bg-[#0a66c2] text-[10px] text-white">in</span>{source}</span>}{action.isUnread && <span className="rounded-full bg-[#edf6ee] px-2 py-1 text-xs font-semibold text-[#2f6047]">Unread</span>}</div><h2 className="mt-3 font-semibold">{action.subject || "(No subject)"}</h2><p className="mt-1 text-sm text-[#607064]">{action.sender || "Unknown sender"}</p></div><time className="text-xs text-[#7b8b7e]">{action.receivedAt ? new Date(action.receivedAt).toLocaleDateString() : "Unknown date"}</time></div><p className="mt-3 text-sm text-[#607064]">{action.priorityReason}</p>{action.snippet && <p className="mt-2 line-clamp-2 text-sm text-[#7b8b7e]">{action.snippet}</p>}{action.actionType === "REVIEW" ? <p className="mt-4 text-sm font-medium text-[#47715b]">Review this update in Gmail before taking action.</p> : action.draftText ? <div className="mt-4"><p className="text-xs font-semibold tracking-[0.1em] text-[#47715b] uppercase">App draft{action.draftModel ? ` · ${action.draftModel}` : ""}</p><textarea className="mt-2 min-h-28 w-full rounded-xl border border-[#dbe5d8] bg-white p-3 text-sm leading-6" defaultValue={action.draftText} /><div className="mt-3 flex items-center gap-3"><button className="rounded-full border border-[#b8cdb8] px-4 py-2 text-sm font-semibold text-[#2f6047]" onClick={() => void onCopy(action)} type="button">{copied === action.gmailMessageId ? "Copied" : "Copy draft"}</button><p className="text-xs text-[#7b8b7e]">Ready to paste into Gmail.</p></div></div> : <div className="mt-4"><button className="rounded-full bg-[#2f6047] px-4 py-2 text-sm font-semibold text-white" disabled={drafting === action.gmailMessageId} onClick={() => void onDraft(action.gmailMessageId)} type="button">{drafting === action.gmailMessageId ? "Writing draft…" : action.actionType === "FOLLOW_UP" ? "Generate follow-up" : "Generate reply"}</button><p className="mt-2 text-xs text-[#7b8b7e]">This sends only this card&apos;s sender, subject, and preview to your selected AI provider.</p></div>}</article>;
}
